{
 "title": "Docker Container & Host Metrics",
 "description": "A simple overview of the most important Docker host and container metrics. (cAdvisor/Prometheus)",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "30s,1m,2m,5m,10m,30m,1h,6h,1d" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(container_cpu_user_seconds_total, job)"
   },
   {
    "name": "node",
    "label": "Host:",
    "query": "label_values(container_cpu_user_seconds_total{job=~\"$job\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Running containers",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(container_last_seen{image!=\"\"})"
    }
   ]
  },
  {
   "title": "CPU Usage on Node",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total[$interval])) * 100",
     "legendFormat": "host"
    }
   ]
  },
  {
   "title": "Free and Used Disk Space on Node",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{fstype=~\"ext4|xfs|btrfs\"}",
     "legendFormat": "{{mountpoint}}"
    },
    {
     "expr": "node_filesystem_size_bytes{fstype=~\"ext4|xfs|btrfs\"} - node_filesystem_avail_bytes{fstype=~\"ext4|xfs|btrfs\"}",
     "legendFormat": "Used Disk Space"
    }
   ]
  },
  {
   "title": "Available Memory on Node",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "node_memory_MemAvailable_bytes", "legendFormat": "Available Memory" },
    {
     "expr": "node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes",
     "legendFormat": "Unavailable Memory"
    }
   ]
  },
  {
   "title": "Disk I/O on Node",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(node_disk_read_bytes_total[$interval])) by (device)",
     "legendFormat": "READ on /{{device}}"
    },
    {
     "expr": "sum(rate(node_disk_written_bytes_total[$interval])) by (device)",
     "legendFormat": "WRITE on /{{device}}"
    }
   ]
  },
  {
   "title": "System Load on Node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "{__name__=~\"^node_load.*\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Network Traffic on Node",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{id=\"/\"}[$interval])) by (id)",
     "legendFormat": "RECEIVED"
    },
    {
     "expr": "- sum(rate(container_network_transmit_bytes_total{id=\"/\"}[$interval])) by (id)",
     "legendFormat": "SENT"
    }
   ]
  },
  {
   "title": "CPU Usage per Container (Stacked)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=~\".+\"}[$interval])) by (name) * 100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory Usage per Container (Stacked)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_rss{name=~\".+\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Sent Network Traffic per Container",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{name=~\".+\"}[$interval])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Cached Memory per Container (Stacked)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_cache{name=~\".+\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Received Network Traffic per Container",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{name=~\".+\"}[$interval])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Version Info",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "cadvisor_version_info",
     "legendFormat": "cAdvisor Version: {{cadvisorVersion}}"
    },
    {
     "expr": "prometheus_build_info",
     "legendFormat": "Prometheus Version: {{version}}"
    },
    {
     "expr": "node_exporter_build_info",
     "legendFormat": "Node-Exporter Version: {{version}}"
    },
    {
     "expr": "cadvisor_version_info",
     "legendFormat": "Docker Version: {{dockerVersion}}"
    },
    { "expr": "cadvisor_version_info", "legendFormat": "Host OS Version: {{osVersion}}" },
    {
     "expr": "cadvisor_version_info",
     "legendFormat": "Host Kernel Version: {{kernelVersion}}"
    }
   ]
  }
 ]
}